### ISSUE TITLE
cci typo

### ISSUE THREAD

**Issue by pchaos** [mapicccy/funcat#2]
series1[series1 == np.inf] = np.nan
                series1[series1 == np.inf] = np.nan
                series = self.func(series0, series1, series2)
"series1[series1 == np.inf] = np.nan" change to :
"series2[series2 == np.inf] = np.nan"

**Comment by mapicccy** [comment]
Thank you for your comment

**Comment by mapicccy** [comment]
fix at commit a66e6e3fcb1a3950d82f7703cf1bef83f19d1ec7
